### ISSUE TITLE
App not working 

### ISSUE THREAD

**Issue by socktow** [Litzuck/lol-esports-spectate#4]

**Comment by leanbinh** [comment]
ông ơi làm sao để cho ra được giao diện như trên ạ

**Comment by leanbinh** [comment]
ông thử xóa cái nền của cái layout đi có thể nó bị chèn lên á

**Comment by Litzuck** [comment]
Sorry for taking so long to answer. If you still want to use this a ready to use client can be found [here](https://github.com/Litzuck/lol-spectator-overlay-client). If you want to use the API, the documentation will be fixed soon, for now you can only try to understand the code by yourself if you really need to.

**Comment by Litzuck** [comment]
Closed because of inactivity.
